name: Check Apple US Stock

on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *"

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Check Apple stock
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python check_stock.py
